import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatGridListModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatSidenavModule,
  MatTableModule,
  MatSortModule,
  MatCheckboxModule,
  MatInputModule,
  MatFormFieldModule,
  MatSnackBarModule,
  MatSelectModule,
  MatExpansionModule,
  MatTabsModule,
  MatProgressSpinnerModule,
  MatDialogModule,
  MatButtonToggleModule,
  MatPaginatorModule,
  MatSlideToggleModule,
  MatTooltipModule,
  MatStepperModule,
  MatListModule,
  MatAutocompleteModule,
  MatRadioModule,
  MatDividerModule,
  MatChipsModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatProgressBarModule,
  MatBadgeModule,
  MatSliderModule
} from '@angular/material';
import { FlexLayoutModule } from '@angular/flex-layout';
import { DateRangePickerModule, CalendarModule, DatePickerModule } from '@syncfusion/ej2-angular-calendars';
import { ButtonModule, CheckBoxModule, RadioButtonModule, SwitchModule } from '@syncfusion/ej2-angular-buttons';
// import { MatSelectSearchModule } from './shared/components/mat-select-search/mat-select-search.module';

@NgModule({
  imports: [
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatGridListModule,
    MatSidenavModule,
    MatTableModule,
    MatSortModule,
    MatCheckboxModule,
    MatInputModule,
    MatFormFieldModule,
    MatSnackBarModule,
    MatSelectModule,
    MatExpansionModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatStepperModule,
    MatListModule,
    MatAutocompleteModule,
    MatRadioModule,
    MatDividerModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatProgressBarModule,
    MatBadgeModule,
    MatSortModule,
    FlexLayoutModule,
    DateRangePickerModule,
    CalendarModule,
    DatePickerModule,
    MatSliderModule,
    // MatSelectSearchModule,
    ButtonModule, CheckBoxModule, RadioButtonModule, SwitchModule
  ],
  exports: [
    FlexLayoutModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatGridListModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSidenavModule,
    MatTableModule,
    MatSortModule,
    MatCheckboxModule,
    MatInputModule,
    MatFormFieldModule,
    MatSnackBarModule,
    MatSelectModule,
    MatExpansionModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatStepperModule,
    MatListModule,
    MatAutocompleteModule,
    MatRadioModule,
    MatBadgeModule,
    MatDividerModule,
    MatChipsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatProgressBarModule,
    DateRangePickerModule,
    CalendarModule,
    DatePickerModule,
    // MatSelectSearchModule,
    ButtonModule, CheckBoxModule, RadioButtonModule, SwitchModule, MatSliderModule
  ]
})
export class MaterialModule { }

